### ISSUE TITLE
[placeholder] Content server future

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/content-service#151]
- ~How are we going to decentralize the system? Do we want to do so?~
The Content Server V3 will be hosted uniquely by Decentraland. Future versions may allow different decentralization mechanisms.

- ~How are we going to distribute the system? Support multi region, fallbacks, etc~
- ~How are we going to make the system reliable?~
- ~How are we going to make the system scalable?~
Current definition for V3 allows to run several server instances, however we may need to clarify how those instances are served from CloudFlare and how the upload process works from different instances.

Current problems:

- ~Race conditions in redis~
V3 won't use Redis.

- ~No procedure to have more than one instance of the service~
Several V3 instances are allowed. We need to clarify the details for that interaction.

- The dapper integration demonstrated the fact that the blockchain related operations should be async, we hide this problem so far with the marketplace API, but when the abstraction fails we are not in a position to handle it. We should consider making the content server deployment process async to be able to cover every possible case.

**Comment by marcosnc** [comment]
Related to: https://trello.com/c/WZCgPWrP
See: https://docs.google.com/document/d/1dFudzgsEbQupJwbohvOSBIk9r7ltV6wC9Kcs6nb6dBU/edit
